/**
 * Permission-Based RBAC 유틸리티.
 *
 * Permission code 상수 (resource:action 형식).
 * 실제 권한 확인은 usePermissions 훅의 hasPermission()으로 수행.
 */

export const PERMISSIONS = {
  STORES_CREATE: "stores:create",
  STORES_READ: "stores:read",
  STORES_UPDATE: "stores:update",
  STORES_DELETE: "stores:delete",
  USERS_CREATE: "users:create",
  USERS_READ: "users:read",
  USERS_UPDATE: "users:update",
  USERS_DELETE: "users:delete",
  ROLES_CREATE: "roles:create",
  ROLES_READ: "roles:read",
  ROLES_UPDATE: "roles:update",
  ROLES_DELETE: "roles:delete",
  EVALUATIONS_CREATE: "evaluations:create",
  EVALUATIONS_READ: "evaluations:read",
  EVALUATIONS_UPDATE: "evaluations:update",
  EVALUATIONS_DELETE: "evaluations:delete",
  SCHEDULES_CREATE: "schedules:create",
  SCHEDULES_READ: "schedules:read",
  SCHEDULES_UPDATE: "schedules:update",
  SCHEDULES_DELETE: "schedules:delete",
  ANNOUNCEMENTS_CREATE: "announcements:create",
  ANNOUNCEMENTS_READ: "announcements:read",
  ANNOUNCEMENTS_UPDATE: "announcements:update",
  ANNOUNCEMENTS_DELETE: "announcements:delete",
  CHECKLISTS_CREATE: "checklists:create",
  CHECKLISTS_READ: "checklists:read",
  CHECKLISTS_UPDATE: "checklists:update",
  CHECKLISTS_DELETE: "checklists:delete",
  TASKS_CREATE: "tasks:create",
  TASKS_READ: "tasks:read",
  TASKS_UPDATE: "tasks:update",
  TASKS_DELETE: "tasks:delete",
  DAILY_REPORTS_CREATE: "daily_reports:create",
  DAILY_REPORTS_READ: "daily_reports:read",
  DAILY_REPORTS_UPDATE: "daily_reports:update",
  DAILY_REPORTS_DELETE: "daily_reports:delete",
  DASHBOARD_READ: "dashboard:read",
  AUDIT_LOG_READ: "completion_log:read",
  INVENTORY_READ: "inventory:read",
  INVENTORY_CREATE: "inventory:create",
  INVENTORY_UPDATE: "inventory:update",
  INVENTORY_DELETE: "inventory:delete",
} as const;
